### ISSUE TITLE
version of tensorflow?

### ISSUE THREAD

**Issue by tobyatgithub** [soutsios/pos-tagger-bert#1]
Hi, I'm wondering what's the version of tensorflow of the notebook?
I ran it recently on tensorflow 2.1 and got 2 errors, 
one being the `tf.Session()` is replaced by `tf.compat.v1.Session()`
and another being `tokenizer = create_tokenizer_from_hub_module()` got error:
`RuntimeError: Exporting/importing meta graphs is not supported when eager execution is enabled. No graph exists when eager execution is enabled.`

**Comment by soutsios** [comment]
From Notepad:
`Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
W0527 23:36:22.545466 140718967228160 __init__.py:56] Some hub symbols are not available because TensorFlow version is less than 1.14`
