### ISSUE TITLE
Dependencies of the Code

### ISSUE THREAD

**Issue by aarsri** [soutsios/pos-tagger-bert#2]
Which versions of tensorflow, bert-tensorflow, and tensorflow_hub did you have when the code was created? I am not able to get the code running due to attribute errors related to these libraries.  Thanks.

Below is one such example:

```
# Instantiate tokenizer
tokenizer = create_tokenizer_from_hub_module()
```

AttributeError                            Traceback (most recent call last)
<ipython-input-34-97952ec55966> in <module>()
      1 # Instantiate tokenizer
----> 2 tokenizer = create_tokenizer_from_hub_module()

2 frames
/usr/local/lib/python3.6/dist-packages/bert/tokenization.py in load_vocab(vocab_file)
    123   vocab = collections.OrderedDict()
    124   index = 0
--> 125   with tf.gfile.GFile(vocab_file, "r") as reader:
    126     while True:
    127       token = convert_to_unicode(reader.readline())

AttributeError: module 'tensorflow' has no attribute 'gfile'

**Comment by soutsios** [comment]
Code was created on April 2018, with tensorflow 1.14.
