### ISSUE TITLE
Error while running "model.load_weights('bert_tagger.h5')" 

### ISSUE THREAD

**Issue by SudeshKumarSK** [soutsios/pos-tagger-bert#4]
Whenever I try to run this "model.load_weights('bert_tagger.h5')" there pops up an error stating "OSError: Unable to open file (unable to open file: name = 'bert_tagger.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)"
![Screenshot 2021-01-25 at 9 04 42 PM](https://user-images.githubusercontent.com/40059066/105727300-f3f6eb00-5f50-11eb-975f-f7f92426cfe0.png)

**Comment by SandyLuXY** [comment]
> Whenever I try to run this "model.load_weights('bert_tagger.h5')" there pops up an error stating "OSError: Unable to open file (unable to open file: name = 'bert_tagger.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)" ![Screenshot 2021-01-25 at 9 04 42 PM](https://user-images.githubusercontent.com/40059066/105727300-f3f6eb00-5f50-11eb-975f-f7f92426cfe0.png)

After every epoch, the file named bert_tagger.h5 will be saved to the current directory. You may want to examine if it exists there.
